START TRANSACTION;
USE `codesign_production`;

INSERT INTO `codesign_production`.`category` (`id`, `name`) VALUES (1, 'Test Category 1');
INSERT INTO `codesign_production`.`category` (`id`, `name`) VALUES (2, 'Test Category 2');
INSERT INTO `codesign_production`.`category` (`id`, `name`) VALUES (3, 'Test Category 3');

INSERT INTO `codesign_production`.`user` (`id`, `name`, `username`) VALUES (1, 'testuser1', 'testuser1');
INSERT INTO `codesign_production`.`user` (`id`, `name`, `username`) VALUES (2, 'testuser2', 'testuser2');
INSERT INTO `codesign_production`.`user` (`id`, `name`, `username`) VALUES (3, 'testuser3', 'testuser3');

INSERT INTO `codesign_production`.`idea` (`id`, `user_id`, `category_id`, `title`, `overview`, `description`) VALUES (1, 1, 1, 'Test Idea 1', 'Test Idea 1 overview', 'Detailed description for Test Idea 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit lacus sit amet libero sodales sit amet sodales tortor vestibulum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse cursus quam in leo tincidunt in dignissim velit cursus. Phasellus non hendrerit dui. Vivamus velit mauris, venenatis eu molestie eu, posuere ac tellus. Morbi gravida hendrerit dolor, a semper ante laoreet id. Quisque luctus ornare sem, dignissim viverra dolor placerat eu. Vestibulum auctor fringilla turpis, et imperdiet sapien convallis eget. Proin eget erat eros, et pretium ipsum. Morbi mi nisl, vulputate nec mattis a, euismod eget massa.');
INSERT INTO `codesign_production`.`idea` (`id`, `user_id`, `category_id`, `title`, `overview`, `description`) VALUES (2, 2, 2, 'Test Idea 2', 'Test Idea 2 overview', 'Detailed description for Test Idea 2. Donec tempus consectetur dignissim. In scelerisque tortor quis lorem semper sed aliquam augue elementum. Phasellus non massa nisi. Quisque tincidunt, eros faucibus venenatis fringilla, arcu erat pretium est, ac iaculis tortor dui pulvinar elit. Ut quis velit hendrerit nunc tempus pharetra eu et lorem. Vestibulum scelerisque, erat sed feugiat ultrices, mauris orci aliquet nisi, a tempor ipsum magna at massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed interdum sem ut diam placerat hendrerit. Donec eget felis nulla, ut ornare velit. Etiam vulputate, neque vitae ultricies adipiscing, diam mauris rutrum erat, sit amet blandit orci diam eu magna. Proin rutrum nunc ac lectus pulvinar eu mollis leo tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.');
INSERT INTO `codesign_production`.`idea` (`id`, `user_id`, `category_id`, `title`, `overview`, `description`) VALUES (3, 3, 3, 'Test Idea 3', 'Test Idea 3 overview', 'Detailed description for Test Idea 3. Suspendisse potenti. Suspendisse congue, odio ac placerat molestie, nunc dolor tincidunt ligula, quis sagittis enim metus nec dolor. Donec vitae magna turpis, ac consequat arcu. Suspendisse nec mauris ac nunc vulputate feugiat sed eget felis. Nullam aliquam magna sed eros bibendum lobortis. Curabitur eu nunc justo. Curabitur ac orci ut mauris ornare lacinia eu viverra augue. Quisque dapibus ultrices libero vel consectetur. Nam ultrices, nisi quis placerat fermentum, turpis nulla tempus libero, ut sagittis massa nibh non mauris. Pellentesque nec mauris et libero cursus malesuada. Duis eget tellus nec ligula accumsan tempor. Donec sed nunc at augue congue faucibus et et ligula. Phasellus sed felis sapien. Cras cursus rutrum nunc, non aliquam ante porta ac.');

INSERT INTO `codesign_production`.`project` (`id`, `category_id`, `incubated`, `hidden`, `name`, `overview`, `description`) VALUES (1, 1, 0, 0, 'Test Project 1', 'Test Project 1 overview', 'Detailed description for Test Project 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit lacus sit amet libero sodales sit amet sodales tortor vestibulum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse cursus quam in leo tincidunt in dignissim velit cursus. Phasellus non hendrerit dui. Vivamus velit mauris, venenatis eu molestie eu, posuere ac tellus. Morbi gravida hendrerit dolor, a semper ante laoreet id. Quisque luctus ornare sem, dignissim viverra dolor placerat eu. Vestibulum auctor fringilla turpis, et imperdiet sapien convallis eget. Proin eget erat eros, et pretium ipsum. Morbi mi nisl, vulputate nec mattis a, euismod eget massa.');
INSERT INTO `codesign_production`.`idea_project` (`id`, `idea_id`, `project_id`) VALUES (1, 1, 1);

INSERT INTO `codesign_production`.`project` (`id`, `category_id`, `incubated`, `hidden`, `name`, `overview`, `description`) VALUES (2, 1, 2, 0, 'Test Short List 1', 'Test Short List 1 overview', 'Detailed description for Test Short List 1. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit lacus sit amet libero sodales sit amet sodales tortor vestibulum. In hac habitasse platea dictumst. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse cursus quam in leo tincidunt in dignissim velit cursus. Phasellus non hendrerit dui. Vivamus velit mauris, venenatis eu molestie eu, posuere ac tellus. Morbi gravida hendrerit dolor, a semper ante laoreet id. Quisque luctus ornare sem, dignissim viverra dolor placerat eu. Vestibulum auctor fringilla turpis, et imperdiet sapien convallis eget. Proin eget erat eros, et pretium ipsum. Morbi mi nisl, vulputate nec mattis a, euismod eget massa.');
INSERT INTO `codesign_production`.`idea_project` (`id`, `idea_id`, `project_id`) VALUES (2, 1, 2);

  
COMMIT;